#!/usr/bin/env bash
# sets up server with a redirect and custom 404
MYHOST=$(cat /etc/hostname)
n4="add_header X-Served-By $MYHOST"
sudo sed -i "29i $n4" /etc/nginx/sites-available/default
service nginx restart
