#!/usr/bin/env bash
#displays holbertonschool 10 times; 9th iteration display hi

counter=1
while [ $counter -le 10 ]
do
	echo "Holberton School"
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	fi
	((counter++))
done

