#!/usr/bin/env bash
#loops from 1 to 10 and displays a message depending on iter

counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((counter++))
done
