#!/usr/bin/env bash
#displays the time from 12 hours and 59 minutes
hour=0
min=1

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	((hour++))
	while [ $min -le 59 ]
	do
		echo $min
		((min++))
	done
	min=1
done
